<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <None Update="README.md">
        <Pack>true</Pack>
        <PackagePath></PackagePath>
      </None>
      <None Update="wow2.png">
        <Pack>true</Pack>
        <PackagePath></PackagePath>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Extensions\" />
    </ItemGroup>

</Project>
