<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Title>WoW2.Backbone.Language.Core.Extensions.Enums.Correlation</Title>
        <PackageId>WoW2.Backbone.Language.Core.Extensions.Enums.Correlation</PackageId>
        <Description>Extension for correlated enums with additional correlation features.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>language, core, enums, extensions, correlation, correlated-enums</PackageTags>
        <Version>9.0.0-alpha.1</Version>
        <Authors>WoW 2.0 Team</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/WoW-2-0-Backbone/Backbone.Language.Core</PackageProjectUrl>
        <RepositoryUrl>https://github.com/WoW-2-0-Backbone/Backbone.Language.Core</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageIcon>wow2.png</PackageIcon>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="wow2.png" Pack="true" PackagePath=""/>
        <None Include="README.md" Pack="true" PackagePath=""/>
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="WoW2.Backbone.Language.Core.Extensions.Enums" Version="9.0.0-alpha.1" />
    </ItemGroup>

</Project>